apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: delivery
type: Opaque
stringData:
  DB_URL: localhost-secret-test
  DB_USER: admin-secret-test
# data:
#   password: test-password # base64 형태로
