apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    resources:
      limits:
        memory: "100Mi"
        cpu: "500m"
    ports:
    - containerPort: 80