apiVersion: v1
kind: Pod
metadata:
  name: label-app-2
  labels:
    group: web
    app: app-2
    version: v1
    env: stage
spec:
  containers:
  - name: webapp-2
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80