apiVersion: v1
kind: Pod
metadata:
  name: label-app-4
spec:
  containers:
  - name: webapp-4
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80