apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deploy
  namespace: delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-app
  template:
    metadata:
      labels:
        app: member-app
    spec:
      containers:
      - name: member-con
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
